# Generated by Django 4.1.1 on 2022-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Macd_Scraping_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_details', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
