# Generated by Django 4.1.1 on 2022-10-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='macd_scraping_data',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
